batch_size: 32
chat_template: false
example_name: sync_random_o
example_num: 50
example_reverse: false
example_seperator: ''
gpu_memory_utilization: 0.8
implimentation: vllm
lke_type: test
max_model_len: 4096
max_new_tokens: 100
model_name: qwen2.5-1.5b
model_path_map: /NS/factual-knowledge-and-hallucination/work/qwu/open_memorize-then-generalize/code_open/util_public/models.json
num_options: 100
open_content: hgp-0
prompt_index: 1
prompt_logprobs: 0
random_seed: 10
save_path: /NS/factual-knowledge-and-hallucination/work/qwu/llm_knowledge/syn_dataset/eval_results/
tensor_parallel_size: 1
test: false
test_data_index: null
test_data_type: test
test_dataset_name: sync_random_o
test_dataset_path: /NS/factual-knowledge-and-hallucination/nobackup/qwu/dataset
test_index_begin: 0
test_index_end: 100
test_relation_id: 50
test_type: close
tokenizer_path: /NS/factual-knowledge-and-hallucination/nobackup/qwu/llm_base_model/meta-llama/Llama-2-7b
train_index_begin: 0
train_index_end: 300
trust_remote_code: true
