compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
fp16: true
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
tpu_use_cluster: false
tpu_use_sudo: false
mixed_precision: "fp16"  # Change to "no" if you don't want mixed precision
